### ISSUE TITLE
Add C/C++ Pattern Printing Programs

### ISSUE THREAD

**Issue by Anubhav-1020** [Ashutosh249/Hacktoberfest-Beginners#1]
Hey @Ashutosh249 Can i add Pattern printing programs to this repo. I am new to open source.. this would be really helpful : )

**Comment by rudraneel18** [comment]
Hi @Ashutosh249 
As a beginner/first time ever contribution in open-source, I would love to add a few yet challenging pattern programs with proper comments in the file for a better understanding of other coders.
Please give me this opportunity to contribute to your repo through hactoberfest 2021 by assigning this task to me.

**Comment by Ashutosh249** [comment]
It's Ok, Any contribution you can do. Thank You
